source 'https://rubygems.org'

gem 'pry', require: 'pry'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'sinatra', require: 'sinatra/base'
gem 'minitest', '~> 5.4.2'
gem 'rack-test', '~> 0.6.2'
gem 'pony', '~> 1.11'
gem 'sequel', '~> 4.16.0'
gem 'nokogiri'
gem 'pg'
